### ISSUE TITLE
用代码设置是失效的。。

### ISSUE THREAD

**Issue by Yexi** [vvinner/BadgeView#2]
布局中设置是可以的，但是用代码设置是失效的

**Comment by vvinner** [comment]
如果布局是继承自ViewGroup(LinearLayout、RelativeLayout)请为该布局设置Background
'android:background="#00000000"'

**Comment by Yexi** [comment]
没有用布局 ，就是用你的例子中的BadgeTextView直接代码设置 不显示。

**Comment by Yexi** [comment]
![这样](http://i2.kiimg.com/1949/e50bda9adbbc0d7a.png)

**Comment by Yexi** [comment]
代码设置不起作用

**Comment by vvinner** [comment]
感谢，改好了。IBadgeView的setColor函数并没有成功设置颜色。
代码已经提交了，重下IBadgeView这个类覆盖就好

**Comment by Yexi** [comment]
好的！谢谢
