### ISSUE TITLE
不好意思，再请教一个问题

### ISSUE THREAD

**Issue by Yexi** [vvinner/BadgeView#3]
如果我想设置间距mPaddingTop ， mPaddingRight ，没办法通过代码设置，只能布局里面设置吗？

**Comment by Yexi** [comment]
我直接在IBadgeView赋值不起作用。

**Comment by vvinner** [comment]
加上去了，你可能要重下Demo。
或者直接查看IBadgeView、BadgeTextView、MainActivity这3个类。
由于这个不是必须设置,将该函数考虑为可选自行配置,而不放入IBadgeViewImpl。

**Comment by Yexi** [comment]
好，非常感谢。
